project_id = "xuohskyiyjfuitzpeevt"

[functions.delete-all-users]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.fix-user-password]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = true
